![raining](4.png)

In [2]:
import os
os.environ["GOOGLE_APPLICATION_CREDENTIALS"]=r"C:\Users\glll4\Downloads\glll4d-f05a4dcba8e9.json"

In [9]:
noaa_gsod.table_schema("gsod2020")

,name,type,mode,description
0,stn,STRING,NULLABLE,Cloud - GSOD NOAA
1,wban,STRING,NULLABLE,WBAN number where applicable--this is the hist...
2,date,DATE,NULLABLE,Date of the weather observations
3,year,STRING,NULLABLE,The year
4,mo,STRING,NULLABLE,The month
5,da,STRING,NULLABLE,The day
6,temp,FLOAT,NULLABLE,Mean temperature for the day in degrees Fahren...
7,count_temp,INTEGER,NULLABLE,Number of observations used in calculating mea...
8,dewp,FLOAT,NULLABLE,Mean dew point for the day in degreesm Fahrenh...
9,count_dewp,INTEGER,NULLABLE,Number of observations used in calculating mea...
10,slp,FLOAT,NULLABLE,Mean sea level pressure for the day in milliba...
11,count_slp,INTEGER,NULLABLE,Number of observations used in calculating mea...
12,stp,FLOAT,NULLABLE,Mean station pressure for the day in millibars...
13,count_stp,INTEGER,NULLABLE,Number of observations used in calculating mea...
14,visib,FLOAT,NULLABLE,Mean visibility for the day in miles to tenths...
15,count_visib,INTEGER,NULLABLE,Number of observations used in calculating mea...
16,wdsp,STRING,NULLABLE,Mean wind speed for the day in knots to tenths...
17,count_wdsp,STRING,NULLABLE,Number of observations used in calculating mea...
18,mxpsd,STRING,NULLABLE,Maximum sustained wind speed reported for the ...
19,gust,FLOAT,NULLABLE,Maximum wind gust reported for the day in knot...
20,max,FLOAT,NULLABLE,Maximum temperature reported during the day in...
21,flag_max,STRING,NULLABLE,Blank indicates max temp was taken from the ex...
22,min,FLOAT,NULLABLE,Minimum temperature reported during the day in...
23,flag_min,STRING,NULLABLE,Blank indicates min temp was taken from the ex...
24,prcp,FLOAT,NULLABLE,Total precipitation (rain and/or melted snow) ...
25,flag_prcp,STRING,NULLABLE,A = 1 report of 6-hour precipitation amount B ...
26,sndp,FLOAT,NULLABLE,Snow depth in inches to tenths--last report fo...
27,fog,STRING,NULLABLE,"Indicators (1 = yes, 0 = no/not reported) for ..."
28,rain_drizzle,STRING,NULLABLE,"Indicators (1 = yes, 0 = no/not reported) for ..."
29,snow_ice_pellets,STRING,NULLABLE,"Indicators (1 = yes, 0 = no/not reported) for ..."
30,hail,STRING,NULLABLE,"Indicators (1 = yes, 0 = no/not reported) for ..."
31,thunder,STRING,NULLABLE,"Indicators (1 = yes, 0 = no/not reported) for ..."
32,tornado_funnel_cloud,STRING,NULLABLE,"Indicators (1 = yes, 0 = no/not reported) for ..."

Турция, Украина, Египет, Казахстан, Мексика, ЮАР, Аргентина, Австралия, Бразилия, Канада

TU, UA, EG, KZ, MX, ZA, AR, AU, BR, CA

In [48]:
import numpy as np
import pandas as pd

import bq_helper 

bqh = bq_helper.BigQueryHelper(active_project= "bigquery-public-data", dataset_name= "noaa_gsod")

START_YEAR = 2000
END_YEAR = 2020

countries = ['TU', 'UA', 'EG', 'KZ', 'MX', 'ZA', 'AR', 'AU', 'BR', 'CA']
stn_query = "SELECT usaf AS stn, name, country, state, lat, lon, elev FROM `bigquery-public-data.noaa_gsod.stations` WHERE country IN ('TU', 'UA', 'EG', 'KZ', 'MX', 'ZA', 'AR', 'AU', 'BR', 'CA') ORDER BY stn"
df_stn = bqh.query_to_pandas_safe(stn_query, max_gb_scanned=5)
stn_list = ','.join(["'"+i+"'" for i in df_stn['stn']])
df_stn = df_stn.drop(['name', 'state', 'lat', 'lon', 'elev'], axis=1)
filename = 'station_country.csv'
df_stn.to_csv(filename, index = False)
print ("Saved {}".format(filename))



for year in range(START_YEAR, END_YEAR):
    query = "SELECT stn, year, AVG(temp) as temp, AVG(dewp) as dewp, AVG(slp) as slp, AVG(stp) as stp, AVG(visib) as visib, sum(prcp) as prcp FROM `bigquery-public-data.noaa_gsod.gsod{}` WHERE stn IN ({})GROUP BY stn, year ORDER BY stn".format(year, stn_list)
    df_wthr = bqh.query_to_pandas_safe(query, max_gb_scanned=5)
    filename = 'weather_{}.csv'.format(year)
    df_wthr.to_csv(filename, index = False)
    print ("Saved {}".format(filename))

Saved station_country.csv
Saved weather_2000.csv
Saved weather_2001.csv
Saved weather_2002.csv
Saved weather_2003.csv
Saved weather_2004.csv
Saved weather_2005.csv
Saved weather_2006.csv
Saved weather_2007.csv
Saved weather_2008.csv
Saved weather_2009.csv
Saved weather_2010.csv
Saved weather_2011.csv
Saved weather_2012.csv
Saved weather_2013.csv
Saved weather_2014.csv
Saved weather_2015.csv
Saved weather_2016.csv
Saved weather_2017.csv
Saved weather_2018.csv
Saved weather_2019.csv